theme: jekyll-theme-minimal
title: Econometría II
description: En este repositorio se encuentra el material del curso de Econometría II del Programa en Economía de la Universidad EAFIT (Medellín-Colombia)