theme: jekyll-theme-minimal
title: Econometría para la Toma de Decisiones
description: En este repositorio se encuentra el material del curso de Econometría para la Toma de Decisiones de la Maestría en Economía Aplicada de la Universidad EAFIT (Medellín-Colombia)